import AppKit

/// 剪贴板自动翻译：每复制一次，就把新内容交给 onChange。
/// macOS 没有剪贴板变化的通知，只能定时看 changeCount 有没有变。
@MainActor
final class ClipboardWatcher {
    /// App 自己写剪贴板时记下当时的 changeCount，免得把自己写进去的译文又翻译一遍
    private static var ownChangeCount = -1

    static func markOwnWrite() {
        ownChangeCount = NSPasteboard.general.changeCount
    }

    /// 接下来一小段时间里的剪贴板变化都不算（模拟复制、粘贴的过程中会连着变几次）
    private static var suspendedUntil = Date.distantPast

    static func suspend(seconds: TimeInterval = 1.5) {
        suspendedUntil = Date().addingTimeInterval(seconds)
    }

    /// 密码管理器等会把内容标成隐私或临时的，这类内容不碰
    private static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    private let onChange: (NSPasteboard) -> Void
    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount

    var isRunning: Bool { timer != nil }

    init(onChange: @escaping (NSPasteboard) -> Void) {
        self.onChange = onChange
    }

    func start() {
        guard timer == nil else { return }
        // 打开之前剪贴板里已有的内容不算
        lastChangeCount = NSPasteboard.general.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.check() }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func check() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        guard pasteboard.changeCount != Self.ownChangeCount, Date() > Self.suspendedUntil else { return }
        // 在快译自己的主窗口里复制的内容不弹
        guard NSWorkspace.shared.frontmostApplication?.processIdentifier != ProcessInfo.processInfo.processIdentifier else { return }
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.privateTypes) else { return }
        onChange(pasteboard)
    }
}
